# This workflow will build, publish, and update the "nightly" tag of Helion.
# GitHub is supposed to use UTC time; 7:35 UTC is 2:35 AM EST

name: Nightly Prerelease

on:
  schedule:
    - cron: '35 7 * * *'
  workflow_dispatch:

jobs:
  buildNightlyLinux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Dotnet Publish Linux
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:SelfContainedRelease=true
    - name: Dotnet Publish Linux AOT
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:AOT=true
      
    - name: Zip Linux Self-Contained
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_SelfContained.zip *
      working-directory: Publish/linux-x64_SelfContained
    - name: Zip Linux AOT
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_AOT.zip *
      working-directory: Publish/linux-x64_AOT

    - name: Update nightly release
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: '*.zip'
