# This workflow will build, publish, and update the "nightly" tag of Helion.
# GitHub is supposed to use UTC time; 7:35 UTC is 2:35 AM EST

name: Nightly Prerelease

on:
  schedule:
    - cron: '35 7 * * *'
  workflow_dispatch:

jobs:
  buildNightlyLinux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Dotnet Publish Linux
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:SelfContainedRelease=true
    - name: Dotnet Publish Linux AOT
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:AOT=true
      
    - name: Zip Linux Self-Contained
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_SelfContained.zip *
      working-directory: Publish/linux-x64_SelfContained
    - name: Zip Linux AOT
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_AOT.zip *
      working-directory: Publish/linux-x64_AOT

    - name: Update nightly release (Linux)
      uses: pyTooling/Actions/releaser@r0
      with:
        tag: nightly
        token: ${{ secrets.GITHUB_TOKEN }}
        files: '*.zip'
        
  buildNightlyWindows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Dotnet Publish Windows
      run: dotnet publish -c Release -r win-x64 Client/Client.csproj -p:SelfContainedRelease=true
    - name: Dotnet Publish Windows AOT
      run: dotnet publish -c Release -r win-x64 Client/Client.csproj -p:AOT=true
      
    - name: Zip Windows Self-Contained
      run: Compress-Archive -Path .\Publish\win-x64_SelfContained\* -DestinationPath .\Helion-${{ github.ref_name }}-win-x64_SelfContained.zip
    - name: Zip Windows AOT
      run: Compress-Archive -Path .\Publish\win-x64_AOT\* -DestinationPath .\Helion-${{ github.ref_name }}-win-x64_AOT.zip

    - name: Update nightly release (Windows)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.zip'
        tag: nightly
        overwrite: true
        file_glob: true